POST http://localhost:8080/db/upload
Content-Type: text/plain

/Users/seansyue/WORKSPACE-Coding/SpringBootProjects/Custom/tf-mysql-detection/out/production/tf.detection.main/tf_inception/test.jpg

###

GET http://localhost:8080/db/all
Accept: */*
Cache-Control: no-cache

###

GET http://localhost:8080/db/sample_inference
Accept: */*
Cache-Control: no-cache

###

GET http://localhost:8080/view/labels
Accept: */*
Cache-Control: no-cache

###

GET http://localhost:8080/view/model_signature
Accept: */*
Cache-Control: no-cache

###

GET http://localhost:8080/test/simple_inference
Accept: */*
Cache-Control: no-cache

###

GET http://localhost:8080/test/dao_inference
Accept: */*
Cache-Control: no-cache

###

GET http://localhost:8080/test/load_fake
Accept: */*
Cache-Control: no-cache

###
